# This is the current set of styling overrides for Dart applications.
# Entries should include a comment explaining why a deviation from the recommended options (from Flutter, below) was made and/or reference a pull request where the discussion took place.
include:
  - package:flutter_lints/flutter.yaml
  - package:very_good_analysis/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # The team determined that 'final' should be used wherever relevant (for any variable that does not change after initialization). See PR #2.
    prefer_final_locals: true
    prefer_final_in_for_each: true
    avoid_final_parameters: false
    prefer_final_parameters: true

plugins:
  explicit_imports:
    version: ^1.0.4
    diagnostics:
      explicit_dart_imports: true
      explicit_flutter_imports: false
      explicit_package_imports: true
      explicit_relative_imports: true
