name: Continuous Deployment for Flutter applications

on:
  push:
    branches:
      - "main"

jobs:
  build-and-deploy:
    uses: fermi-ad/.github/.github/workflows/flutter-deploy.yaml@f28e79514083cd7d1bc53405ae4794d52b39d9d0
    secrets: inherit
