name: Continuous Deployment for Flutter applications

on:
  push:
    branches:
      - "main"

jobs:
  build-and-deploy:
    uses: fermi-ad/.github/.github/workflows/flutter-deploy.yaml@b99946ba8722aeb25ac95245fa01862054748f92
    secrets: inherit
    permissions:
      contents: write
    # Optional: Change to true to pull in git submodules during build
    with:
      pull-git-submodules: false
