name: CI (Enclosure Status)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    uses: fermi-ad/.github/.github/workflows/flutter-integration.yaml@44dd481076c7b39cb78a4d3bbd59a21b711c24bb
    secrets: inherit
    permissions:
      contents: write
    with:
      test: smoke_test # matches test/acceptance/smoke_test.dart


